package com.SE.customer;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CustomerInfoManagement.java
//  @ Date : 2019-05-31
//  @ Author : 
//
//

public class CustomerInfoManagement {

	private DBManager db;

	public CustomerInfoManagement() {
		db = new DBManager();

	}

	public boolean insertCustomerInfo(CustomerInfo c) {

		return db.insertCustomerInfo(c);
	}

	public boolean modifyCustomerInfo(CustomerInfo c) {

		return db.modifyCustomerInfo(c);
	}

	public boolean deleteCustomerInfo(String customerCode) {
		return db.deleteCustomerInfo(customerCode);
	}

	public List<CustomerInfo> lookupCustomerInfo(String customerCode) {
		List<CustomerInfo> customerInfoList = db.lookupCustomerInfo(customerCode);
		return customerInfoList;
	}

	public List<CustomerInfo> interestedLookupCustomerInfo(String customerCode) {
		List<CustomerInfo> customerInfoList = db.interestedLookupCustomerInfo(customerCode);
		return customerInfoList;
	}

}

/*
 * public void modifyCustomerInfo(Object customerInfo) {
 * 
 * String SQL = "UPDATE CODE SET departName ='"; SQL += departName +
 * "' WHERE codeName ='"; SQL += codeName + "'";
 * 
 * System.out.println(SQL); try { state.executeUpdate(SQL); return 1; } catch
 * (Exception e) { System.out.println("db_UPDATECODE : " + e.getMessage()); }
 * 
 * return 0; }
 * 
 * 
 * 
 * public void requestInterestedCustomerCheck() {
 * 
 * }
 * 
 * public void requestInterestedCustomerCheck(Object customerInfo) {
 * 
 * }
 * 
 * private void checkOverlap(Object customerInfo) {
 * 
 * }
 * 
 * private void checkType(Object customerInfo) {
 * 
 * } }
 */
