package com.SE.customer;

import java.sql.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CustomerInfo.java
//  @ Date : 2019-05-31
//  @ Author : 

public class CustomerInfo {
	private String customerCode;
	private String customerName;
	private String phoneNum;
	private String address;
	private String birthDay;

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setBirthday(String birthDay) {
		this.birthDay = birthDay;
	}

	public String getCustomerCode() {
		return customerCode;
	}

	public String getCustomerName() {
		return customerName;
	}

	public String getPhoneNum() {
		return phoneNum;
	}

	public String getAddress() {
		return address;
	}

	public String getBirthDay() {
		return birthDay;
	}
}
